services:
  bpf-asset-management:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: bpf-asset-system
    restart: unless-stopped
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
    environment:
      - TZ=Asia/Jakarta
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    networks:
      - bpf-network

networks:
  bpf-network:
    driver: bridge